<?xml version="1.0" encoding="utf-8"?><Database Name="QL_THIETBIDIENTU" Class="QLThietBiDienTuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-AV\SQLEXPRESS;Initial Catalog=QL_THIETBIDIENTU;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QL_THIETBIDIENTUConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HangHoa" Member="HangHoas">
    <Type Name="HangHoa">
      <Column Name="MaHH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenHH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NoiSX" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HangHoa_HoaDon" Member="HoaDons" ThisKey="MaHH" OtherKey="MaHH" Type="HoaDon" />
      <Association Name="NhomHang_HangHoa" Member="NhomHang" ThisKey="MaNhom" OtherKey="MaNhom" Type="NhomHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhomHang" Member="NhomHangs">
    <Type Name="NhomHang">
      <Column Name="MaNhom" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NhomHang_HangHoa" Member="HangHoas" ThisKey="MaNhom" OtherKey="MaNhom" Type="HangHoa" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaHH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HangHoa_HoaDon" Member="HangHoa" ThisKey="MaHH" OtherKey="MaHH" Type="HangHoa" IsForeignKey="true" />
      <Association Name="NhanVien_HoaDon" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="NhanVien_HoaDon" Member="HoaDons" ThisKey="MaNV" OtherKey="MaNV" Type="HoaDon" />
    </Type>
  </Table>
</Database>